WITH FRIENDS AS ( 
SELECT FW.OTHER_FRIEND
FROM Users u
INNER JOIN Friends_With FW ON FW.Friend = U.u_id
WHERE U.u_id = '1'
),
TRIPS_ACCEPTED_BY_FRIENDS AS (
SELECT T.T_ID, F.OTHER_FRIEND
FROM  Friends F
INNER JOIN Invite_Trip IT ON IT.Invited_Users = F.Other_Friend
INNER JOIN Trip T ON T.T_ID = IT.T_ID
WHERE IT.Accepted = 1
AND PRIVACY_FLAG = 0
),

TRIPS_CREATED_BY_FRIENDS AS (
SELECT T.T_ID, F.OTHER_FRIEND
FROM Friends F
INNER JOIN Trip T ON T.Creator = F.Other_Friend
WHERE PRIVACY_FLAG = 0
),

TRIPS_BY_FRIENDS AS (
SELECT *
FROM TRIPS_CREATED_BY_FRIENDS TCBF UNION  SELECT * FROM TRIPS_ACCEPTED_BY_FRIENDS TABF
)

SELECT T.T_ID, TBF.OTHER_Friend AS Friend, T.START_DATE, T.END_DATE, T.Location, T.Name AS Trip_Name, U.First_name, U.Last_name
FROM TRIPS_BY_FRIENDS TBF
INNER JOIN Trip T ON T.T_ID = TBF.T_ID
INNER JOIN Users U ON TBF.Other_Friend = U.U_ID